<% if request.Cookies("dev")<>"" then %><span class="dev"><%= pRS("FUENTE") %></span> &nbsp; <% end if %>
<%if pRS("FUENTE")="PROPERTY WEB" then%><img src="/img/fuentes/web.gif" alt="PROPERTYWEB" height="30" align="absmiddle"><%end if%>
<%if pRS("FUENTE")="DTZ IBERICA" then%><a href="https://www.dtz.com" target="_blank"><img src="/img/fuentes/dtz.gif" height="30" align="absmiddle" border="0"></a><a href="https://www.lavozdegalicia.com" target="_blank"><img src="/img/fuentes/la-voz-de-galicia.gif" width="81" height="30" border="0" align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="NORTE DE CASTILLA" then%><a href="https://www.nortecastilla.es/edicion/" target="_blank"><img src="/img/fuentes/norte_castilla.gif" width="81" height="30" border="0"  align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="KNIGHT FRANK" then%><a href="https://www.knightfrank.es/" target="_blank"><img src="/img/fuentes/kf.gif" width="81" height="30" border="0"  align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="EUROSTAR" then%><a href="https://www.nortecastilla.es/edicion/" target="_blank"><img src="/img/fuentes/eurostar.gif" width="81" height="30" border="0"  align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="VIA INMOBILIARIA" then%><a href="" target="_blank"><img src="/img/fuentes/VIAINMO.JPG" width="81" height="30" border="0"  align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="ALIMARKET" then%><a href="https://www.alimarket.es/" target="_blank"><img src="/img/fuentes/alimarket2.gif" width="81" height="30" border="0"  align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="BBVA" then%><a href="https://www.bbva.es/" target="_blank"><img src="/img/fuentes/BBVA.gif" width="81" height="30" border="0"  align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="TASAMADRID" then%><a href="https://www.tasamadrid.com/valora_online/valoraciononl.aspx" target="_blank"><img src="/img/fuentes/tasamadrid.jpg" width="81" height="30" border="0"  align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="HERALDO DE ARAGON" then%><a href="https://www.heraldo.es/" target="_blank"><img src="/img/fuentes/heraldoarag.gif" width="81" height="30" border="0"  align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="ASOCIACION HIPOTECARIA ESPA�OLA" then%><a hrefhttps:p://www.ahe.es/bocms/sites/ahe/pages/Home.jsp?mID=19" target="_blank"><img src="/img/fuentes/AHE.gif" width="81" height="30" border="0"  align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="DIARIO DE AVISOS" then%><a href="https://www.diariodeavisos.com/" target="_blank"><img src="/img/fuentes/avisos.gif" width="81" height="30" border="0"  align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="CAMBRA" then%><a href="https://www.cambrapropbcn.com/" target="_blank"><img src="/img/fuentes/cambra.gif" width="81" height="30" border="0"  align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="IDEALISTA" then%><a href="https://www.idealista.com" target="_blank"><img src="/img/fuentes/idealista.gif" width="81" height="30" border="0"  align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="EXPANSION" then%><a href="https://www.recoletos.es/expansion" target="_blank"><img src="/img/fuentes/expansion.gif"  align="absmiddle" border="0"></a><%end if%>
<%if pRS("FUENTE")="CINCO DIAS" then%><a href="https://www.cincodias.es" target="_blank"><img src="/img/fuentes/cinco-dias.gif" width="81" height="30" border="0"  align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="EL PAIS" then%><a href="https://www.elpais.es" target="_blank"><img src="/img/fuentes/el-pais.gif" width="81" height="30" border="0"  align="absmiddle" ></a><%end if%>
<%if LEFT(pRS("FUENTE"),3)="ABC" then%><a href="https://www.abc.es" target="_blank"><img src="/img/fuentes/abc.gif" width="81" height="30" border="0" align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="EL MUNDO" then%><a href="https://www.el-mundo.es" target="_blank"><img src="/img/fuentes/el-mundo.gif" width="81" height="30" border="0"  align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="SUR" then%><a href="https://www.diariosur.es" target="_blank"><img src="/img/fuentes/el-sur.gif" width="81" height="30" border="0" align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="LA  VANGUARDIA" or pRS("FUENTE")="LA VANGUARDIA" then%><a href="https://www.lavanguardia.es" target="_blank"> <img src="/img/fuentes/la vanguardia.gif" width="81" height="30" border="0" align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="COHISPANIA" or pRS("FUENTE")="COHISPANIA" then%><a href="https://www.cohispania.com/" target="_blank"> <img src="/img/fuentes/COHISPANIA.gif" width="81" height="30" border="0" align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="COLEGIO OFICIAL DE AGENTES DE LA PROPIEDAD INMOBILIARIA DE BARCELONA " then%><a href="https://www.apibcn.com/" target="_blank"> <img src="/img/fuentes/API.gif" width="81" height="30" border="0" align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="IDEAL" then%><a href="https://www.ideal.es" target="_blank"><img src="/img/fuentes/ideal.gif" height="30" align="absmiddle" border="0"></a><%end if%>
<%if pRS("FUENTE")="LA NUEVA ESPA�A" then%><a hrefhttps:p://www.lanuevaespana.es" target="_blank"><img src="/img/fuentes/la-nueva-espana.gif" width="81" height="30" border="0" align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="EUROPROPERTY" then%><a href="https://www.europrop.com" target="_blank"><img src="/img/fuentes/europroperty.gif" height="30" align="absmiddle" border="0"></a><%end if%>
<%if pRS("FUENTE")="LA GACETA DE LOS NEGOCIOS" or pRS("FUENTE")="GACETA DE LOS NEGOCIOS" then%><a href="https://www.negocios.com" target="_blank"><img src="/img/fuentes/la gaceta de los negocios.gif" align="absmiddle" border="0"></a><%end if%>
<%if pRS("FUENTE")="LA VOZ DE galicia" then%><a href="https://www.lavozdegalicia.es" target="_blank"><img src="/img/fuentes/la-voz-de-galicia.gif" width="81" height="30" border="0"  align="absmiddle" /></a><%end if%>
<%if pRS("FUENTE")="LA VOZ DE ASTURIAS" then%><a href="https://www.elperiodico.es/asturias" target="_blank"><img src="/img/fuentes/la-voz-de-asturias.gif" width="81" height="30" border="0" align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="DIARIO DE MALLORCA" then%><a href="https://www.diariodemallorca.es" target="_blank"><img src="/img/fuentes/diario-de-mallorca.gif" width="81" height="30" border="0" align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="LA VERDAD" then%><a href="https://www.la-verdad.com" target="_blank"><img src="/img/fuentes/la-verdad.gif" width="81" height="30" border="0" align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="EL DIARIO VASCO" then%><a href="https://www.diariovasco.com" target="_blank"><img src="/img/fuentes/el-diario-vasco.gif" alt="ireal" width="81" height="30" border="0" align="absmiddle" /></a><%end if%>
<%if pRS("FUENTE")="LAS PROVINCIAS" then%><a href="https://www.lasprovincias.es" target="_blank"><img src="/img/fuentes/las-provincias.gif" width="81" height="30" border="0"  align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="DIARIO DE BURGOS" then%></a><a href="https://www.diariodeburgos.es" target="_blank"><img src="/img/fuentes/diario-de-burgos.gif" width="81" height="30" border="0" align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="HOY" then%><a href="https://www.hoy.es" target="_blank"><img src="/img/fuentes/hoy.gif" height="30" align="absmiddle" border="0" /></a><a href="https://www.hoy.es/" target="_blank"><%end if%>
<%if pRS("FUENTE")="METROS 2" then%><a href="https://www.metros2.com" target="_blank"><img src="/img/fuentes/metros2.gif" height="30" align="absmiddle" border="0"></a><%end if%>
<%if pRS("FUENTE")="CANARIAS7" then%><a href="https://www.canarias7.es" target="_blank"><img src="/img/fuentes/canarias7.gif" height="30" align="absmiddle" border="0"></a><%end if%>
<%if pRS("FUENTE")="AGUIRRE NEWMAN" then%><a href="https://www.aguirrenewman.es" target="_blank"><img src="/img/fuentes/aguirre-newman.gif" width="81" height="30" border="0" align="absmiddle" ></a><%end if%>
<%if pRS("FUENTE")="EL DIARIO MONTA�ES" then%><a hrefhttps:p://www.eldiariomontanes.es" target="_blank"><img src="/img/fuentes/eldiariomontanes.gif" height="30" align="absmiddle" border="0"></a><%end if%>
<%if pRS("FUENTE")="JONES LANG LASALLE" or pRS("FUENTE")="JLL" then%><a href="https://www.joneslanglasalle.com/" target="_blank"><img src="/img/fuentes/joneslang.gif" height="30" align="absmiddle" border="0"></a><%end if%>
<%if pRS("FUENTE")="JONES LANG LASALLE PORTUGAL" then%><a href="https://www.joneslanglasalle.pt" target="_blank"><img src="/img/fuentes/joneslangpt.jpg" height="30" align="absmiddle" border="0"></a><%end if%>
<%if pRS("FUENTE")="IREA" then%><a href="https://www.elcorreodigital.com/vizcaya/" target="_blank"><img src="/img/fuentes/irea.gif" height="30" align="absmiddle" border="0" /></a><%end if%>
<%if pRS("FUENTE")="alimarket" then%><a href="https://www.alimarket.es/" target="_blank"><img src="/img/fuentes/alimarket.gif" height="30" align="absmiddle" border="0"></a><%end if%>
<%if pRS("FUENTE")="jordaguasch" then%><a href="https://www.jordaguasch.es/" target="_blank"><img src="/img/fuentes/jordaguasch.gif" height="30" align="absmiddle" border="0"></a><%end if%>
<%if pRS("FUENTE")="JORDA & GUASCH" then%><a href="https://www.jordaguasch.es/" target="_blank"><img src="/img/fuentes/jordaguasch.gif" height="30" align="absmiddle" border="0"></a><%end if%>
<%if pRS("FUENTE")="CB RICHARD ELLIS" then%><a href="https://www.cbrichardellis.es/" target="_blank"><img src="/img/fuentes/cbre.gif" height="30" align="absmiddle" border="0"></a><%end if%>
<%if pRS("FUENTE")="20 MINUTOS" then%><a href="https://www.20minutos.es/" target="_blank"><img src="/img/fuentes/20.gif" height="30" align="absmiddle" border="0"></a><%end if%>
<%if pRS("FUENTE")="EFE" then%><a href="https://www.efe.es/" target="_blank"><img src="/img/fuentes/EFE.gif" height="30" align="absmiddle" border="0"></a><%end if%>
<%if pRS("FUENTE")="INE" then%><a href="https://www.ine.es/" target="_blank"><img src="/img/fuentes/INE.gif" height="30" align="absmiddle" border="0" /></a><%end if%>
<%if pRS("FUENTE")="EL CORREO" then%><a href="https://www.elcorreodigital.com/vizcaya/" target="_blank"><img src="/img/fuentes/elcorreo.gif" height="17" align="absmiddle" border="0" /></a><%end if%>
<%if pRS("FUENTE")="NUEVA ALCARRIA" then%><a href="https://www.aache.com/na/" target="_blank"><img src="/img/fuentes/nuevaalcarria.gif" height="17" align="absmiddle" border="0" /></a><%end if%>
<%if pRS("FUENTE")="DIARIO DE NAVARRA" then%><a href="https://www.diariodenavarra.es/" target="_blank"><img src="/img/fuentes/diarionavarra.gif" height="17" align="absmiddle" border="0" /></a><%end if%>
<%if pRS("FUENTE")="EL FARO DE CEUTA" then%><a href="https://www.elfaroceutamelilla.com/" target="_blank"><img src="/img/fuentes/ELFAROCEUTA.gif" height="17" align="absmiddle" border="0" /></a><%end if%>
<%if pRS("FUENTE")="EL NORTE DE CASTILLA " then%><a href="https://www.nortecastilla.es/" target="_blank"><img src="/img/fuentes/NORTECAS.gif" height="17" align="absmiddle" border="0" /></a><%end if%>
<%if pRS("FUENTE")="EC HARRIS" then%><a href="https://www.echarris.com/international/index.asp?c=13" target="_blank"><img src="/img/fuentes/echarris.gif" height="30" align="absmiddle" border="0" /></a><%end if%>
<%if pRS("FUENTE")="EL INMOBILIARIO MES A MES" then%><a href="https://www.google.com/search?hl=es&rls=GBSA%2CGBSA%3A2006-02%2CGBSA%3Aen&q=%22EL+INMOBILIARIO+MES+A+MES%22&lr=" target="_blank"><img src="/img/fuentes/ELINMO.gif" height="30" align="absmiddle" border="0" /></a><%end if%>
<%if pRS("FUENTE")="DIARIO DE CADIZ" then%><a href="https://www.diariodecadiz.com/" target="_blank"><img src="/img/fuentes/diariocadiz.gif" height="30" align="absmiddle" border="0" /></a><%end if%>
<%if pRS("FUENTE")="CUSHMAN & WAKEFIELD" then%><a href="https://www.cushwake.com/cwglobal/jsp/globalHomeSSO.jsp" target="_blank"><img src="/img/fuentes/CUSMAN.gif" height="30" align="absmiddle" border="0" /></a><%end if%>
<%if pRS("FUENTE")="BANCO DE ESPA�A" then%><a hrefhttps:p://www.bde.es/" target="_blank"><img src="/img/fuentes/bancode.gif" height="30" align="absmiddle" border="0" /></a><%end if%>
<%if pRS("FUENTE")="PUBLITURIS" then%><a href="https://www.publituris.pt/" target="_blank"><img src="/img/fuentes/publituris.gif" height="30" align="absmiddle" border="0" /></a><%end if%>
<%if pRS("FUENTE")="LANZA" then%><a href="https://www.lanzadigital.com/" target="_blank"><img src="/img/fuentes/LANZA.gif" height="30" align="absmiddle" border="0" /></a><%end if%>
<%if pRS("FUENTE")="ASOCIACION ESPA�OLA DE CENTROS COMERCIALES" then%><a hrefhttps:p://www.aedecc.com" target="_blank"><img src="/img/fuentes/aecc.gif" height="30" align="absmiddle" border="0" /></a><%end if%>
<%if pRS("FUENTE")="AECC" then%><a href="https://www.aedecc.com" target="_blank"><img src="/img/fuentes/aecc.gif" height="30" align="absmiddle" border="0" /></a><%end if%>
<%if pRS("FUENTE")="DIARIO VASCO" then%><a href="https://www.diariovasco.com/" target="_blank"><img src="/img/fuentes/diariovasco.gif" height="30" align="absmiddle" border="0" /></a><%end if%>
<%if pRS("FUENTE")="LA RIOJA" then%><a href="https://www.larioja.com/" target="_blank"><img src="/img/fuentes/LARIOJA.gif" height="17" align="absmiddle" border="0" /></a><%end if%>
<%if pRS("FUENTE")="ASPRIMA" then%><a href="https://www.asprima.es/plt_Home.aspx" target="_blank"><img src="/img/fuentes/ASPRIMA.gif" height="17" align="absmiddle" border="0" /></a><%end if%>
<%if pRS("FUENTE")="COLEGIO DE REGISTRADORES DE ESPA�A" then %><a hrefhttps:p://www.registradores.org" target="_blank"><img src="/img/fuentes/registradores.gif" height="30" align="absmiddle" border="0" /></a><%end if%><%if pRS("FUENTE")="BNP PARIBAS" then%><img src="/img/fuentes/bnp_paribas.jpg" alt="BNP PARIBAS" height="65" align="absmiddle"><%end if%>